name: Build
on: [push, pull_request]

env:
  EM_VERSION: 3.1.61
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v4
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EM_VERSION }}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Package
      run: npm pack

    - name: Upload package tarball
      uses: actions/upload-artifact@v4
      with:
        name: package-tarball
        path: js-fatfs-*.tgz
