name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm

    - name: Install WebAssembly toolchain
      run: sudo apt-get install --no-install-recommends clang lld

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Package
      run: npm pack

    - name: Upload package tarball
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: js-fatfs-*.tgz
