name: Publish
on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v7

    - name: Install WebAssembly toolchain
      run: sudo apt-get install --no-install-recommends clang lld

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
